# Generated by Django 4.2.4 on 2023-11-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={},
        ),
        migrations.AlterField(
            model_name='slider',
            name='banner',
            field=models.ImageField(upload_to='sliders/'),
        ),
    ]
